# Generated by Django 2.0.7 on 2020-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_auto_20200912_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
