# Generated by Django 2.0.7 on 2020-09-19 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_auto_20200919_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 6, 41, 55, 643866, tzinfo=utc)),
        ),
    ]
