# Generated by Django 2.0.7 on 2020-09-19 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_auto_20200919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
